first

diff --git a/.github/workflows/clonerepo.yml b/.github/workflows/clonerepo.yml
--- a/.github/workflows/clonerepo.yml
+++ b/.github/workflows/clonerepo.yml
@@ -14,33 +14,56 @@ jobs:
       - name: Checkout this repository
         uses: actions/checkout@v4
 
-    #   - name: Set up Git
-    #     run: |
-    #       git config --global user.name "GitHub Actions"
-    #       git config --global user.email "actions@github.com"
+      - name: Set up Git
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
 
-    #   - name: Clone Azure DevOps repository
-    #     env:
-    #       AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
-    #     run: |
-    #       git clone https://defoortd:${{ secrets.AZURE_DEVOPS_PAT }}@dev.azure.com/defoortd/bachelorproef%20Emre/_git/bachelorproef%20Emre bpPoc
+      - name: Set Org
+      # Change the value of GITHUB_OWNER to the name of the organization you want to configure.
+        run: |
+          echo "emre-poc" >> $GITHUB_ENV
 
-    #   - name: Create GitHub repository
-    #     env:
-    #       GITHUB_PAT: ${{ secrets.ADMIN_PAT }}
-    #     run: |
-    #       curl -X POST -H "Authorization: token ${{ secrets.ADMIN_PAT }}" \
-    #           -H "Accept: application/vnd.github.v3+json" \
-    #           -d '{"name":"bpPOC","private":false}' \
-    #           https://api.github.com/user/repos || echo "Repository creation failed or already exists"
+      - name: Clone Azure DevOps repository
+        env:
+          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
+        run: |
+          git clone https://defoortd:${{ secrets.AZURE_DEVOPS_PAT }}@dev.azure.com/defoortd/bachelorproef%20Emre/_git/bachelorproef%20Emre bpPoc
+
+      # - name: Create GitHub repository
+      #   env:
+      #     GITHUB_PAT: ${{ secrets.ADMIN_PAT }}
+      #   run: |
+      #     curl -X POST -H "Authorization: token ${{ secrets.ADMIN_PAT }}" \
+      #         -H "Accept: application/vnd.github.v3+json" \
+      #         -d '{"name":"bpPOC","private":false}' \
+      #         https://api.github.com/user/repos || echo "Repository creation failed or already exists"
   
-    #   - name: Push to GitHub repository
-    #     env:
-    #       GITHUB_PAT: ${{ secrets.ADMIN_PAT }}
-    #     run: |
-    #       cd bpPoc
-    #       git remote add github https://github.com/Emre-Igten/bpPOC.git
-    #       git push https://x-access-token:${{ secrets.ADMIN_PAT }}@github.com/Emre-Igten/bpPOC.git main
+      # - name: Push to GitHub repository
+      #   env:
+      #     GITHUB_PAT: ${{ secrets.ADMIN_PAT }}
+      #   run: |
+      #     cd bpPoc
+      #     git remote add github https://github.com/Emre-Igten/bpPOC.git
+      #     git push https://x-access-token:${{ secrets.ADMIN_PAT }}@github.com/Emre-Igten/bpPOC.git main
+
+      - name: Create GitHub repository in organization
+        env:
+          GITHUB_PAT: ${{ secrets.ADMIN_PAT }}
+        run: |
+          curl -X POST -H "Authorization: token ${{ secrets.ADMIN_PAT }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            -d '{"name":"bpPOC","private":false}' \
+            https://api.github.com/orgs/${{ env.GITHUB_OWNER }}/repos || echo "Repository creation failed or already exists"
+
+      - name: Push to GitHub repository
+        env:
+          GITHUB_PAT: ${{ secrets.ADMIN_PAT }}
+        run: |
+          cd bpPoc
+          git remote add github https://github.com/${{ env.GITHUB_OWNER }}/bpPOC.git
+          git push https://x-access-token:${{ secrets.ADMIN_PAT }}@github.com/${{ env.GITHUB_OWNER }}/bpPOC.git main
+
 
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v1
